import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import { Loader, Card, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  if (data !== null) {
    if (data?.length > 0) {
      // console.log(data);
      return data.map((post) => <Card {...post} />);
    }
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [images, setImages] = useState([null]);
  const [searchText, setSearchText] = useState("");
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setsearchTimeout] = useState(null);
  useEffect(() => {
    const fetchPost = async () => {
      setLoading(true);
      try {
        const response = await fetch(
          "https://ai-image-gen-ojxe.onrender.com/api/v1/post",
          {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
            },
          }
        );

        if (response.status === 200) {
          const result = await response.json();

          setImages(result.data.reverse());
        }
      } catch (error) {
        console.log(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPost();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setsearchTimeout(
      setTimeout(() => {
        const searchResult = images.filter((post) => {
          return (
            post.prompt.toLowerCase().includes(searchText.toLowerCase()) ||
            post.name.toLowerCase().includes(searchText.toLowerCase())
          );
        });
        setSearchedResults(searchResult);
      }, 500)
    );
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div className="">
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">
          browse through a collection of imaginative and visually stunning
          images generated by image-gen
        </p>
      </div>
      <div className="mt-16 ">
        <FormField
          LabelName="Search Post"
          type="text"
          name="text"
          placeholder="Search Post"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-xl mb-3">
                Showing Result for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}

            <div className="grid lg:grid-cols-4 sm:grid-col-3 xs:grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No search result found"
                />
              ) : (
                <RenderCards data={images} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};
export default Home;
